services:
  web:
    build: .
    command: ./bin/rails server -b 0.0.0.0
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    environment:
      - ACCU_WEATHER_API_KEY=${ACCU_WEATHER_API_KEY}
      - RAILS_ENV=${RAILS_ENV}

  worker:
    build: .
    command: ./bin/delayed_job start
    environment:
      - ACCU_WEATHER_API_KEY=${ACCU_WEATHER_API_KEY}
      - RAILS_ENV=${RAILS_ENV}
